version: "3.8"
name: real-time-text-area

services:
  node_app:
    # image: "api"
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: real-time-text-area-api
    environment:
      - PORT=5000
    ports:
      - 5000:5000

  react_app:
    # image: "client"
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: real-time-text-area-client
    ports:
      - 5173:5173
    depends_on:
      - node_app
    environment:
      - PORT=http://node_app
